### ISSUE TITLE
Tutorial isn't updated to the latest versison of WA

### ISSUE THREAD

**Issue by LarsIpsen** [IBM-Bluemix-Docs/assistant#125]
The Tutorial is not updated to the latest version of the WA service, as an example does the Turtoroal still using "Worksspaces" instead of skills.

**Comment by michelle-miller** [comment]
@LarsIpsen from what url did you see a reference to workspaces?

**Comment by LarsIpsen** [comment]
HI
I found it in all the tutorials in the documentation, e.g.here:
https://console.bluemix.net/docs/services/conversation/tutorial.html#tutorial
But you can also find it all the tutorials, also in the intro of the of the tutorial like here: https://console.bluemix.net/docs/services/conversation/index.html#about

**Comment by LarsIpsen** [comment]
There is also demo's from the garage, that need to be updated, like this 
https://www.ibm.com/cloud/garage/demo/try-watson-assistant, but not sure if those demo's belongs to your team

**Comment by michelle-miller** [comment]
The garage info is not owned by the WA ID team. not sure how to report that/to whom.
the product documentation for Watson Assistant has moved to here: https://console.bluemix.net/docs/services/assistant/index.html.
you can find the new tutorial docs, etc. there.  
(we are in the process of getting redirects set up so you would automatically be sent to the correct set of docs.)

**Comment by LarsIpsen** [comment]
Thx, make sense, you just need to be aware of, that the "Getting started link" on the front page still point to the old documentation.
<img width="712" alt="screen shot 2018-11-12 at 21 11 10" src="https://user-images.githubusercontent.com/11677728/48372673-9c496d80-e6bf-11e8-8585-756316c41416.png">

**Comment by michelle-miller** [comment]
Ah. thanks for the screen shot. The link now redirects to the new content. But, you are right. We should edit the link so it goes to the correct url directly. I'll find out who owns that and ask them to update it. Thanks!
