### ISSUE TITLE
the service.message body is not correct in the V2 tutorial 

### ISSUE THREAD

**Issue by nnworkspace** [IBM-Bluemix-Docs/assistant#151]
In the code example 2, in the service.message body, the parameter "input" is missing, which will bring us a very stupid assistant which understands nothing. Please see the nodejs example in the API doc:

https://console.bluemix.net/apidocs/assistant-v2?language=node#data-handling

**Comment by rrberry** [comment]
Can you be more specific about where you are seeing this issue? I am not sure which tutorial or example you are looking at.

**Comment by nnworkspace** [comment]
oh sorry for the confusion, I meant the document on this page, and the code example 2:

https://console.bluemix.net/docs/services/assistant/api-client.html?programming_language=javascript#building-a-client-application

**Comment by nnworkspace** [comment]
ah sorry, it was my mistake. I copied the code from example 1 and worked further in the response part following example 2.  The the code I saw was still from example 1. Yes this issue can be closed. Thanks for the reply!
