### ISSUE TITLE
"Adding a node with slots" tutorial link not working

### ISSUE THREAD

**Issue by bclerico** [IBM-Bluemix-Docs/assistant#154]
Link address is: https://cloud.ibm.com/services/conversation/tutorial-slots.html

![image](https://user-images.githubusercontent.com/8126772/49880254-bdee5f80-fdf9-11e8-8010-8c26b52fd705.png)

**Comment by bclerico** [comment]
Same issue with the "old" portal.

https://cloud.ibm.com/services/conversation/tutorial-slots.html

**Comment by michelle-miller** [comment]
where did you get that url from?

**Comment by michelle-miller** [comment]
try this url instead: https://console.bluemix.net/docs/services/assistant/tutorial-slots.html 
(but, i'd like to know where you got that link, in case we have a bad link to it from one of our other doc pages. if so, i'd want to fix it.)

**Comment by bclerico** [comment]
> try this url instead: https://console.bluemix.net/docs/services/assistant/tutorial-slots.html
> (but, i'd like to know where you got that link, in case we have a bad link to it from one of our other doc pages. if so, i'd want to fix it.)

the link you provided works

**Comment by michelle-miller** [comment]
Links from the getting started that you get to from the IBM Cloud dashboard should now be working. Thanks again for calling our attention to the problem! Much appreciated.
