### ISSUE TITLE
Bad link - Watson SDK for Java

### ISSUE THREAD

**Issue by rodalton** [IBM-Bluemix-Docs/assistant#225]
The text below includes a bad link: 

`Note: Make sure you have installed the Watson SDK for Java`

Points to https://github.com/watson-developer-cloud/java-sdk/blob/develop/README.md

Should point to https://github.com/watson-developer-cloud/java-sdk/blob/master/README.md

**Comment by michelle-miller** [comment]
@rrberry looks like this is in the api-client.md topic

**Comment by michelle-miller** [comment]
looks like this is fixed.
