### ISSUE TITLE
Add Github Repo Link - Watson Assistant customer service demo

### ISSUE THREAD

**Issue by Oliver-I** [IBM-Bluemix-Docs/assistant#254]
On the Sample Apps page (page https://cloud.ibm.com/docs/services/assistant?topic=assistant-sample-apps#sample-apps), the section titled "Simple chat app" has a link to the github repository. 

For the section "Watson Assistant customer service demo", can we also add the link to the github repository (https://github.com/watson-developer-cloud/assistant-demo)?

**Comment by michelle-miller** [comment]
Great idea. Added. Thanks for the github repo url.
