### ISSUE TITLE
"output: The dialog response to return to the user."

### ISSUE THREAD

**Issue by obgvts** [IBM-Bluemix-Docs/assistant#262]
Hi,

On the https://cloud.ibm.com/docs/services/assistant?topic=assistant-dialog-runtime#dialog-runtime. I think the following section that talks about what **output** looks like maybe confusing to reader. If I'm not wrong, it is actually the dialog JSON configuration for output json.

```
{
"output": {
  "generic": [
    {
      "values": [
        {
          "text": "This is my response text."
        }
      ],
      "response_type": "text",
      "selection_policy": "sequential"
    }
  ]
}
}
```

Regards,
Vincent Ong

**Comment by michelle-miller** [comment]
Thanks for the comment. Updated the topic to make it clear that what we show is the dialog JSON editor representation of the context, input, and output objects.
