### ISSUE TITLE
Continuing issue with IBM Assistant Videos

### ISSUE THREAD

**Issue by jurijnyu** [IBM-Bluemix-Docs/assistant#299]
On each and every training video or for that matter any initialization  Watson Assistant, it starts off with the Welcome Dialog Node, That node says " If Assistant Recognizes Welcome".  Well that seems incongruous because it is the Assistant that is conveying the welcome. Or if this is an entry intent, where is it defined in the intents list ?  What am I missing ?

**Comment by michelle-miller** [comment]
i'm not sure i understand the question. but, when you create a dialog for the first time, two nodes are added to the dialog tree for you. you can delete them if you want. they are added as a courtesy to make it easier to see how the dialog works by using the Try it out pane. The welcome node is created with a special condition called welcome. it is a sort of special built-in intent. you can read more about special conditions from here: https://cloud.ibm.com/docs/services/assistant?topic=assistant-dialog-overview#dialog-overview-special-conditions. i hope that helps.
