### ISSUE TITLE
The document needs to be updated.

### ISSUE THREAD

**Issue by imankurpatel000** [IBM-Bluemix-Docs/assistant#333]
The document at the following link needs to be updated.
https://cloud.ibm.com/docs/services/assistant?topic=assistant-api-client&programming_language=javascript

// Set up Assistant service wrapper.
const service = new AssistantV2({
  iam_apikey: '{apikey}', // replace with API key
  url: '{url}', // replace with your watson assistant URL. This is missing.
  version: '2019-02-28',
});

Also, the document mentions using npm install watson-developer-cloud which should be npm install ibm-watson.

**Comment by rrberry** [comment]
Updated the doc to show the current package names for Node and Python.

The `url` parameter is not required (by default the Dallas public service endpoint is used). It's omitted here for the sake of simplicity, but you will need to add it if you need to use a different service endpoint.
